name: Version

on:
  pull_request: 
    branches:
      -main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Git Version
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        uses: codacy/git-version@2.5.4